<?php
    $currentStoreView = $block->getCurrentStoreId();
    $storeViewsDB = $block->getStoreViewsDB();
    $backgroundColor = $block->getButtonColor($currentStoreView);
    $invertColor = strrev($backgroundColor);
?>

<?php if(in_array($currentStoreView, $storeViewsDB)): ?>
    <style>
        .product-item-actions button.action.tocart.primary, .actions button.action.tocart.primary{
            background-color: #<?php echo $backgroundColor; ?> !important;
            border-color: #<?php echo $backgroundColor; ?> !important;
            color: #<?php echo $invertColor; ?> !important;
        }.product-item-actions button.action.tocart.primary:hover, .actions button.action.tocart.primary:hover{
            background-color: #<?php echo $invertColor; ?> !important;
            border-color: #<?php echo $invertColor; ?> !important;
            color: #<?php echo $backgroundColor; ?> !important;
        }

        button.primary{
            background-color: #<?php echo $backgroundColor; ?> !important;
            border-color: #<?php echo $backgroundColor; ?> !important;
            color: #<?php echo $invertColor; ?> !important;
        }button.primary:hover{
            background-color: #<?php echo $backgroundColor; ?> !important;
            border-color: #<?php echo $backgroundColor; ?> !important;
            color: #<?php echo $invertColor; ?> !important;
        }
    </style>
<?php endif; ?>
