<?php
/** @var \Hibrido\Consolebutton\Block\ButtonColor $block */

// Obtém o ID da store view atual.
$currentStoreView = $block->getCurrentStoreId();

// Obtém a lista de store views no banco de dados.
$storeViewsDB = $block->getStoreViewsDB();

// Obtém a cor de fundo do botão com base na store view atual.
$backgroundColor = $block->getButtonColor($currentStoreView);

// Inverte a cor para usar como texto.
$invertColor = strrev($backgroundColor);
?>

<?php if (in_array($currentStoreView, $storeViewsDB)): ?>
    <style>
        /* Estilos CSS para botões com base na cor de fundo */
        .product-item-actions button.action.tocart.primary,
        .actions button.action.tocart.primary {
            background-color: #<?= $backgroundColor; ?> !important;
            border-color: #<?= $backgroundColor; ?> !important;
            color: #<?= $invertColor; ?> !important;
        }

        .product-item-actions button.action.tocart.primary:hover,
        .actions button.action.tocart.primary:hover {
            background-color: #<?= $invertColor; ?> !important;
            border-color: #<?= $invertColor; ?> !important;
            color: #<?= $backgroundColor; ?> !important;
        }

        button.primary {
            background-color: #<?= $backgroundColor; ?> !important;
            border-color: #<?= $backgroundColor; ?> !important;
            color: #<?= $invertColor; ?> !important;
        }

        button.primary:hover {
            background-color: #<?= $backgroundColor; ?> !important;
            border-color: #<?= $backgroundColor; ?> !important;
            color: #<?= $invertColor; ?> !important;
        }
    </style>
<?php endif; ?>
